{
 "title": "Cluster Core Resource Status",
 "description": "Node와 Pod CPU, Memory 수치를 모니터링 하기 위한 대시보드",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Resource & Pod Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allocatable Requests - CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"}) by (node) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\", resource=\"cpu\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Allocatable Requests - Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (node) / sum(kube_node_status_allocatable{resource=\"memory\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(kube_node_status_allocatable{resource=\"pods\",node!=\"k8sm2\"})",
     "legendFormat": "allocatable"
    },
    { "expr": "sum(kube_pod_info{}) by (node)", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"Pending|Unknown|Failed|\"}) by (phase, pod)",
     "legendFormat": "{{phase}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Allocatable Limits - CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (node) / sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Allocatable Limits - Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (node) / sum(kube_node_status_allocatable{resource=\"memory\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{}) by (container)",
     "legendFormat": "Waiting: {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{}unless on(namespace, pod)kube_pod_owner{owner_kind=~\"Job|CronJob\"}) by (container)",
     "legendFormat": "Terminated: {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"}) by (container, namespace, pod)",
     "legendFormat": "OOMKilled: {{namespace}}/{{pod}}"
    }
   ]
  },
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "w": 3, "x": 0, "y": 16, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(kube_node_info{})" }
   ]
  },
  {
   "title": "Node Status",
   "type": "timeseries",
   "gridPos": { "w": 5, "x": 3, "y": 16, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=~\"OutOfDisk|DiskPressure|MemoryPressure|PIDPressure|NetworkUnavailable\", status=\"true\"}) by (condition, node)",
     "legendFormat": "{{condition}}: {{node}}"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"false\"}) by (node)",
     "legendFormat": "NotReady: {{node}}"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable) by (node)",
     "legendFormat": "UnSchedulable: {{node}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "w": 5, "x": 8, "y": 16, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "w": 5, "x": 13, "y": 16, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{} / node_memory_MemTotal_bytes{}) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "w": 6, "x": 18, "y": 16, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{fstype!=\"tmpfs\", mountpoint=\"/\"} / node_filesystem_size_bytes{fstype!=\"tmpfs\", mountpoint=\"/\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pod Resource Usage by Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "w": 3, "x": 0, "y": 23, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "w": 5, "x": 3, "y": 23, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "w": 5, "x": 8, "y": 23, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "w": 5, "x": 19, "y": 23, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "rx: {{pod}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "tx: {{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage (PVC)",
   "type": "timeseries",
   "gridPos": { "w": 6, "x": 13, "y": 23, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim!=\"\"} / kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim!=\"\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}