{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-teams-alarm
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ms-teams-alarm
                port:
                  number: 80
{{- end }}
