apiVersion: v1
kind: Service
metadata:
  name: ms-teams-alarm
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ms-teams-alarm
  ports:
    - port: 80
      targetPort: {{ .Values.env.appPort }}
