namespace: infra-manager

image:
  repository: <BUILD_NODE_IP>:8082/apps/ms-teams-alarm  # Nexus Docker 레지스트리 (192.168.50.x)
  tag: "v26.03.17"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: nexus-secret

replicaCount: 1

nodeSelector:
  kubernetes.io/hostname: "k8sworker1"

env:
  notifierType: "msteams"
  appPort: "8000"

secret:
  msTeamsWebhookUrl: "https://xxxxx.webhook.office.com/webhookb2/<WEBHOOK_ID>"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

ingress:
  enabled: false
  className: "nginx"
  host: ""
